---
- name: Install required Configurations
  hosts: localhost # Replace with your target hosts or group
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python
      apt:
        name: python3  # Install Python 3
        state: present  # Ensure Python is installed

    - name: Install Pip for Python 3
      apt:
        name: python3-pip  # Install Pip for Python 3
        state: present  # Ensure Pip is installed

    - name: Install python3.8-venv package
      apt:
        name: python3.8-venv
        state: present
    
    - name: Install PostgreSQL client
      become: yes
      apt:
        name: postgresql-client
        state: present

    - name: Check if psql is in PATH
      shell: |
        if ! command -v psql &> /dev/null
        then
          export PATH="$PATH:/usr/bin"
        fi
      args:
        executable: /bin/bash

    - name: install Azure cli 
      apt:
        name: azure-cli
        state: present
        
    
    - name: Install software-properties-common for terraform installation
      shell: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      
    - name: Install HarshiCorp GPG key for terraform installation
      shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
       
    - name: Add official HashiCorp repository to system for terraform installation
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
        https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
        sudo tee /etc/apt/sources.list.d/hashicorp.list
      
    - name: Download the package information from HashiCorp.
      shell: |
        sudo apt update 
        sudo apt-get install terraform
 
    - name: Add Azure CLI and Terraform to PATH
      lineinfile:
        dest: "~/.bashrc"
        line: |
          export PATH="$PATH:/usr/bin/azure-cli:/usr/bin/terraform"
        state: present
      become: yes

    
    - name: Install kubectl
      shell: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl


