apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: django 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: django-cicd:148
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 8000
        args: ["gunicorn", "dcrm.wsgi:application", "--bind", "0.0.0.0:8000"]
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-name
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-user
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-password
              key: db_password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-host
              key: db_host
        - name: DB_PORT
          value: "5432"

---

apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: django 
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
