apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app # it is used in django-app-service 
    spec:
      containers:
      - name: django-app
        image: mayank7833/midnight:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - containerPort: 8000
        CMD ["gunicorn", "dcrm.wsgi:application", "--bind", "0.0.0.0:8000"]
        env:
        - name: DATABASE_NAME
          value: "${DB_NAME}"
        - name: DB_USER
          value: "${DB_USER}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"
        - name: DB_HOST
          value: "newserver.postgres.database.azure.com"
        - name: DB_PORT
          value: "5432"

---

apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
